Craigslist/Craigslist/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

Craigslist/core/urls.py
from core.views import home, new_search
from django.urls import path

app_name = "core"

urlpatterns = [
    path('', home, name="home"),
    path('new_search', new_search, name="new-search"),
]

Craigslist/core/models.py
from django.db import models


class Search(models.Model):
    search = models.CharField(max_length=500, blank=True)
    created = models.DateField(auto_now=True)

    def __str__(self):
        return self.search

    class Meta:
        verbose_name_plural = 'Searches'

Craigslist/core/forms.py
from core.models import Search
from django import forms


class SearchForm(forms.ModelForm):
    class Meta:
        model = Search
        fields = ('search',)
        widgets = {}

Craigslist/core/views.py
import asyncio
from core.forms import SearchForm
from core.models import Search
from django.shortcuts import render

from .utils import searching


async def home(request):
    return render(request, 'core/home.html', context={})


async def new_search(request):
    if request.method == 'POST':
        forms = SearchForm(request.POST)
        if forms.is_valid():
            stuff_to_frontend = await searching(forms.cleaned_data['search'])
            # TODO:  <19-01-21, coderj001>
            # django sync_to_async support need to save query
            # forms.save()
        return render(
            request,
            'core/search.html',
            context={
                'forms': forms,
                'content_data': stuff_to_frontend
            }
        )
    else:
        forms = SearchForm()
        return render(request, 'core/search.html', context={'forms': forms})

Craigslist/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Craigslist:{% block title %} {% endblock title %}</title>
  </head>
  <link rel="icon" href="{% static 'img/title.ico' %}" />
  <!-- custom css -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!--Import Google Icon Font-->
  <link
    href="https://fonts.googleapis.com/icon?family=Material+Icons"
    rel="stylesheet"
  />
  <!--Import materialize.css-->
  <link
    type="text/css"
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
    media="screen,projection"
  />

  <body>
    {% block content %} {% endblock content %}
  </body>
  <!--JavaScript at end of body for optimized loading-->
  <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"
  ></script>
  <!-- custom js -->
  <script src="{% static 'js/main.js' %}"></script>
</html>

Craigslist/templates/core/home.html
{% extends 'base.html' %}
<!-- title area -->
{% block title %} Home {% endblock title %}
<!-- content area -->
{% block content %}
<!-- background -->
{% include 'core/slogan.html' %}
<!-- search button -->
<div class="center">
  <a
    class="waves-effect waves-light btn btn-large purple darken-2"
    href="{% url 'core:new-search' %}"
    ><i class="material-icons left">arrow_drop_down</i>CLICK</a
  >
</div>
{% endblock content %}

Craigslist/templates/core/result.html
<div class="container">
  <h2>Result:</h2>
  <br />
</div>
<br />
<br />
<div class="row">
  {% for dat in content_data %}
      {% if dat %}
          <div class="col s12 m4 l4">
            <div class="card hoverable">
              <div class="card-image">
                <img src="{{dat.img}}" />
                <span class="card-title">{{dat.title}}</span>
              </div>
              <div class="card-content">
                <p>{{dat.body | escape | safe}}</p>
              </div>
              <div class="card-action">
                <a href="{{dat.url}}">This is a link</a>
              </div>
            </div>
          </div>
      {% endif %}
  {% endfor %}
</div>

Craigslist/templates/core/search.html
{% extends 'base.html' %}
<!-- title area -->
{% block title %} Search {% endblock title %}
<!-- content area -->
{% block content %}
<!-- background  -->
{% include 'core/slogan.html' %}
<div class="container">
  <div class="center">
    <h2>Search...</h2>
    <form action="{% url 'core:new-search' %}" method="post">
      <!-- vuln -->
      {% csrf_token %}
      <!-- check -->
      <div class="row">
        <div class="input-field col s12 m12 l12">
          {% if forms %}
          <!-- django form -->
          {{ forms }}
          <!-- end checked -->
          {% endif %}
        </div>
      </div>
      <div class="center">
        <button class="waves-effect waves-light btn btn-large purple darken-2">
          <i class="material-icons left">search</i>SEARCH
        </button>
      </div>
    </form>
  </div>
</div>
<br />
<br />
<br />
<!-- check -->
{% if content_data %}
<!-- call for result template -->
{% include 'core/result.html' with content_data=content_data %}
<!-- checked -->
{% endif %}
<!-- end -->
{% endblock content %}

Craigslist/templates/core/slogan.html
<!-- navbar -->
<nav class="nav-extended purple darken-2">
  <div class="container nav-wrapper">
    <a href="#" class="brand-logo">Craigslist</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href="{% url 'core:home' %}">Home</a></li>
    </ul>
  </div>
</nav>

<div class="container">
  <h1 class="center-align">Welcome To My Craigslist!!</h1>
  <h2 class="center-align">Search???..</h2>
  <div class="row">
    <div class="col s4">
      <div class="center">
        <i class="large material-icons">flash_on</i>
        <p>First Craigslist Web Scraper</p>
        <p class="purple-text text-light center">
          Scraper Right Away Here With Beautiful User Interface
        </p>
      </div>
    </div>
    <div class="col s4">
      <div class="center">
        <i class="large material-icons">camera</i>
        <p>Filter Your Searches</p>
        <p class="purple-text text-light center">
          We Build Functionality To Filter Based On Pricing
        </p>
      </div>
    </div>
    <div class="col s4">
      <div class="center">
        <i class="large material-icons">chrome_reader_mode</i>
        <p>Sexy Front-End To Craigslist</p>
        <p class="purple-text text-light center">We Build With Love</p>
      </div>
    </div>
  </div>
</div>